CREATE DATABASE somativa_sophia;
CREATE DATABASE IF NOT EXISTS somativa_sophia;
USE somativa_sophia;


CREATE TABLE IF NOT EXISTS CLIENTES(
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CPF VARCHAR(60) NOT NULL UNIQUE,
TELEFONE VARCHAR(60),
DATA_NASCIMENTO INT(60)
);


CREATE TABLE IF NOT EXISTS VEICULOS(
ID_VEICULO INT AUTO_INCREMENT PRIMARY KEY,
TIPO_VEICULO ENUM ('CARRO', 'MOTO') DEFAULT 'CARRO',
MARCA VARCHAR(60) NOT NULL,
MODELO VARCHAR(60) NOT NULL,
SERVICO VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS MARCAS(
ID_MARCA INT AUTO_INCREMENT PRIMARY KEY,
DATA_FUNDACAO INT(60),
COR VARCHAR(60) NOT NULL,
LOCALIZACAO VARCHAR(60) NOT NULL,
COMBUSTIVEL_TIPO VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS MODELOS(
ID_MODELO INT AUTO_INCREMENT PRIMARY KEY,
NOME_MARCA VARCHAR(60) NOT NULL,
ANO_LANCAMENTO INT(60),
GARANTIA VARCHAR(60) NOT NULL,
CATEGORIA VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
NOME_FUNCIONARIO VARCHAR(60) NOT NULL,
TELEFONE VARCHAR(60),
DATA_NASCIMENTO INT(60),
TIPO_FUNCIONARIO ENUM ('MECANICO', 'FAXINEIRO', 'LOGISTICA') DEFAULT 'MECANICO',
PAGAMENTO DECIMAL(5,2) DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS SERVICOS(
ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
TIPO_SERVICO VARCHAR(60) NOT NULL,
PROBLEMA VARCHAR(60) NOT NULL,
PRECO DECIMAL(5,2) DEFAULT 0.00,
HORA_PREVISTA_TERMINO INT(60)
);

CREATE TABLE IF NOT EXISTS PECAS(
 ID_PECA INT AUTO_INCREMENT PRIMARY KEY,
 MODELO_PECA VARCHAR(60) NOT NULL,
 MARCA_PECA VARCHAR(60) NOT NULL,
 FORNECEDOR_PECA VARCHAR(60) NOT NULL,
 PRECO DECIMAL(5,2) DEFAULT 0.00
 );

CREATE TABLE IF NOT EXISTS ORDEM_SERVICO(
ID_ORDEMSERVICO INT AUTO_INCREMENT PRIMARY KEY,
NOME_CLIENTE VARCHAR(60) NOT NULL,
TIPO_SERVICO VARCHAR(60) NOT NULL,
PRECO DECIMAL(5,2) DEFAULT 0.00,
HORA_PREVISTA_TERMINO INT(60)
);

CREATE TABLE IF NOT EXISTS PAGAMENTO(
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
NOME_CLIENTE VARCHAR(60) NOT NULL,
FORMA_PAGAMENTO ENUM ('CREDITO', 'DEBITO', 'PIX','FISICO') DEFAULT 'CREDITO',
DATA_VENCIMENTO INT(60),
VALOR_PAGO INT(60)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
TELEFONE VARCHAR(60),
PRODUTOS ENUM ('PNEU', 'CHAVE DE FENDA', 'TINTA') DEFAULT 'PNEU',
PRECO DECIMAL(5,2) DEFAULT 0.00
);

SHOW TABLES;

ALTER TABLE CLIENTES ADD CAMPO_TESTE1 VARCHAR(100);
ALTER TABLE VEICULOS ADD CAMPO_TESTE1 VARCHAR(100);
ALTER TABLE MARCAS ADD CAMPO_TESTE1 VARCHAR(100);
ALTER TABLE MODELOS ADD CAMPO_TESTE1 VARCHAR(100);
ALTER TABLE FUNCIONARIOS ADD CAMPO_TESTE1 VARCHAR(100);
ALTER TABLE SERVICOS ADD CAMPO_TESTE1 VARCHAR(100);
ALTER TABLE PECAS ADD CAMPO_TESTE1 VARCHAR(100);
ALTER TABLE ORDEM_SERVICO ADD CAMPO_TESTE1 VARCHAR(100);
ALTER TABLE PAGAMENTO ADD CAMPO_TESTE1 VARCHAR(100);
ALTER TABLE FORNECEDORES ADD CAMPO_TESTE1 VARCHAR(100);
ALTER TABLE CLIENTES DROP COLUMN CAMPO_TESTE1;
ALTER TABLE VEICULOS DROP COLUMN CAMPO_TESTE1;
ALTER TABLE MARCAS DROP COLUMN CAMPO_TESTE1;
ALTER TABLE MODELOS DROP COLUMN CAMPO_TESTE1;
ALTER TABLE FUNCIONARIOS DROP COLUMN CAMPO_TESTE1;
ALTER TABLE SERVICOS DROP COLUMN CAMPO_TESTE1;
ALTER TABLE PECAS DROP COLUMN CAMPO_TESTE1;
ALTER TABLE PAGAMENTO DROP COLUMN CAMPO_TESTE1;
ALTER TABLE FORNECEDORES DROP COLUMN CAMPO_TESTE1;
ALTER TABLE CLIENTES DROP COLUMN CAMPO_TESTE1;


RENAME TABLE MODELOS TO MODELOS_FAB;





DROP DATABASE somativa_sophia;



